name: Migrate Me To Backend Pipeline
on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy_pipeline:
    name: Deploy Pipeline
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Mock Server
        run: npm run mock:server &

      - name: Create .env file

        run: |
          touch .env
          echo CONSUMER_API_KEY=${{ secrets.CONSUMER_API_KEY }} >> .env
          echo CONSUMER_API_KEY_SECRET=${{ secrets.CONSUMER_API_KEY_SECRET }} >> .env

      - name: Tests
        run: npm test

      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: Migrate Me To Backend
          heroku_email: jibran.web@gmail.com
